fix: need to correctly get the shell

diff --git a/Makefile_kind b/Makefile_kind
--- a/Makefile_kind
+++ b/Makefile_kind
@@ -240,8 +240,8 @@ endif
 
 .PHONY: check-context
 check-context:
-	-CURRENT_CONTEXT=$(kubectl config current-context)
-	-if [ "$${CURRENT_CONTEXT}" != "kind-$${CLUSTER_NAME}" ]; then \
-		echo "Error: kubectl context is not set to kind-$${CLUSTER_NAME}"; \
-		exit 1; \
-	fi
+    CURRENT_CONTEXT:=$(shell kubectl config current-context)
+    if [ "$${CURRENT_CONTEXT}" != "kind-$${CLUSTER_NAME}" ]; then \
+        echo "Error: kubectl context is not set to kind-$${CLUSTER_NAME}"; \
+        exit 1; \
+    fi
