fix: putting a context check into the make each time kubectl or helm is used

diff --git a/Makefile_kind b/Makefile_kind
--- a/Makefile_kind
+++ b/Makefile_kind
@@ -3,20 +3,19 @@ CLUSTER_NAME := $(NAME)
 
 OS := $(shell uname -s | tr '[:upper:]' '[:lower:]')
 ARCH := $(shell uname -m | sed 's/x86_64/amd64/')
-BASEDIRS := baseline extractcsv
-##EXTRA_DIRS := tracesenumpre tracesenum
-DIRS :=    tracessshpre tracesssh tracesscppre tracesscp tracesk8sclientpre tracesk8sclient tracessymlinkpre tracessymlink
+
+DIRS :=  signal  tracessshpre tracesssh 
 
 .EXPORT_ALL_VARIABLES:
 
 ##@ Scenario
 
 .PHONY: all-up
-all-up: cluster-up tetragon-install redpanda redpanda-kind-smb redpanda-wasm vector ssh-install rbac sc-deploy port-forward traces
+all-up: cluster-up redpanda tetragon-install vector traces redpanda-wasm-hosted  ssh-install rbac sc-deploy port-forward traces
 
 ## Run this in a second shell to observe the STDOUT
 .PHONY: secondshell-on
-secondshell-on: 
+secondshell-on: check-context
 	-kubectl logs -n kube-system -l app.kubernetes.io/name=tetragon -c export-stdout -f | \
 	jq 'select( .process_kprobe != null and .process_kprobe.process.pod.namespace == "default" ) | "\(.time) \(.process_kprobe.policy_name) \(.process_kprobe.function_name) \(.process_kprobe.process.binary) \(.process_kprobe.process.arguments) \(.process_kprobe.process.pod.namespace) \(.process_kprobe.args[] | select(.sock_arg != null) | .sock_arg)"'
 
@@ -30,29 +29,29 @@ teardown: stop-port-forwarding sc-delete cluster-down
 
 .PHONY: cluster-up
 cluster-up: kind ## Create the kind cluster
-	-$(KIND) create cluster --name $(CLUSTER_NAME) --config config/kind-config.yaml
+	$(KIND) create cluster --name $(CLUSTER_NAME) --config config/kind-config.yaml
 
 .PHONY: cluster-down
-cluster-down: kind ## Delete the kind cluster
+cluster-down: kind helm check-context ## Delete the kind cluster
 	-$(HELM) uninstall vector -n vector
 	-$(HELM) uninstall redpanda-src -n redpanda
 	-$(HELM) uninstall cert-manager -n cert-manager
 	-$(HELM) uninstall tetragon -n kube-system
 	-sleep 10
-	-$(KIND) delete cluster --name $(CLUSTER_NAME)
+	$(KIND) delete cluster --name $(CLUSTER_NAME)
 
 .PHONY: stop-port-forwarding
-stop-port-forwarding:
+stop-port-forwarding: check-context
 	-lsof -ti:5555 | xargs kill -9
 
 .PHONY: attack-delete
-attack-delete:
+attack-delete: check-context
 	-kubectl delete po my-pod
 	-kubectl delete pvc my-claim-vol 
 	-kubectl delete pv my-volume-vol
 
 .PHONY: sc-delete
-sc-delete:
+sc-delete: check-context
 	-kubectl delete po my-pod
 	-kubectl delete pvc my-claim-vol 
 	-kubectl delete pv my-volume-vol
@@ -61,13 +60,13 @@ sc-delete:
 ##@ Redpanda
 
 .PHONY: redpanda
-redpanda:
+redpanda: helm check-context
 	-$(HELM) repo add jetstack https://charts.jetstack.io
 	-$(HELM) repo update
 	-$(HELM) upgrade --install cert-manager jetstack/cert-manager --set installCRDs=true --namespace cert-manager  --create-namespace
 	-$(HELM) repo add redpanda https://charts.redpanda.com
 	-$(HELM) repo update
-	-$(HELM) upgrade --install redpanda-src redpanda/redpanda -n redpanda --create-namespace --values redpanda/values.yaml --set logging.logLevel=debug
+	-$(HELM) upgrade --install redpanda-src redpanda/redpanda -n redpanda --create-namespace --values redpanda/values.yaml 
 	while [ "$$(kubectl -n redpanda get po -l app.kubernetes.io/name=redpanda -o jsonpath='{.items[0].metadata.generateName}')" != "redpanda-src-" ]; do \
 		sleep 5; \
    	echo "Waiting for Redpanda pod to be created."; \
@@ -76,20 +75,20 @@ redpanda:
 	-kubectl exec -it -n redpanda redpanda-src-0 -c redpanda -- /bin/bash -c "rpk topic create cr1"
 
 
-.PHONY: redpanda-wasm
-redpanda-wasm:
-#	-kubectl exec -it -n redpanda redpanda-src-0 -c redpanda -- /bin/bash -c "rpk topic create baseline && rpk topic alter-config baseline --set cleanup.policy=compact"
-	@for dir in $(DIRS); do \
-		cd redpanda/$$dir/ && go mod tidy && $(RPK) container start; $(RPK) transform build && cd ../.. ;\
-		kubectl exec -it -n redpanda redpanda-src-0 -c redpanda -- /bin/bash -c "rpk topic create $$dir" ;\
-		kubectl exec -it -n redpanda redpanda-src-0 -c redpanda -- /bin/bash -c "mkdir -p /tmp/$$dir" ;\
-		kubectl cp redpanda/$$dir/transform.yaml redpanda/redpanda-src-0:/tmp/$$dir/. ;\
-		kubectl cp redpanda/$$dir/$$dir.wasm redpanda/redpanda-src-0:/tmp/$$dir/. ;\
-		kubectl --namespace redpanda exec -i -t redpanda-src-0 -c redpanda -- /bin/bash -c "cd /tmp/$$dir/ && rpk transform deploy" ;\
-	done
+
 	
+.PHONY: redpanda-wasm-hosted
+redpanda-wasm-hosted:	check-context
+	@for dir in $(DIRS); do \
+		kubectl exec -it -n redpanda redpanda-src-0 -c redpanda -- /bin/bash -c "rpk topic create $$dir" ;\
+		kubectl --namespace redpanda exec -i -t redpanda-src-0 -c redpanda -- /bin/bash -c "rpk transform deploy --file https://raw.githubusercontent.com/k8sstormcenter/honeycluster/main/prebuilt/$$dir.wasm --name $$dir --input-topic=cr1 --output-topic=$$dir --var language=tinygo-no-goroutines " ;\
+	done
+
+
+## The below two tasks are not used in the k8sstormcenter at the moment, we are discussing how to best make the baseline dynamically adaptable
+
 .PHONY: redpanda-kind-smb
-redpanda-kind-smb:
+redpanda-kind-smb: check-context
 	sed -i 's/REDPANDA_CONTAINER_ID/$(shell docker exec -it $(CLUSTER_NAME)-control-plane ls /var/log/containers | grep "redpanda-src-0_redpanda_redpanda-[a-z0-9]*\.log" | sed -e 's/redpanda-src-0_redpanda_redpanda-//' | sed -e 's/\.log//')/g' redpanda/kind-smb/transform/transform.go
 	-cd redpanda/kind-smb/transform; $(RPK) container start; $(RPK) transform build; cd ../../..;
 	-kubectl exec -it -n redpanda redpanda-src-0 -c redpanda -- /bin/bash -c "mkdir -p /tmp/kind-smb/ && rpk topic create smb" 
@@ -100,7 +99,7 @@ redpanda-kind-smb:
 
 
 .PHONY: redpanda-keys
-redpanda-keys:
+redpanda-keys: check-context
 	-kubectl logs -n redpanda redpanda-src-0 -c redpanda |grep "transform - extractcsv" > redpanda/extractcsv/extract
 	-cut -f 11- -d ' ' redpanda/extractcsv/extract >> keys.csv
 	-cat -n keys.csv | sort -uk2 | sort -nk1 | cut -f2-  > uniquekeys.csv 
@@ -111,7 +110,7 @@ redpanda-keys:
 ##@ Tetragon
 
 .PHONY: tetragon-install
-tetragon-install: helm
+tetragon-install: helm check-context
 	-$(HELM) repo add cilium https://helm.cilium.io
 	-$(HELM) repo update
 	-$(HELM) upgrade --install tetragon cilium/tetragon -n kube-system --set tetragon.grpc.enabled=true --set tetragon.grpc.address=localhost:54321
@@ -123,7 +122,7 @@ tetragon-install: helm
 
 
 .PHONY: vector
-vector:
+vector: helm check-context
 	-$(HELM) repo add vector https://helm.vector.dev
 	-$(HELM) upgrade --install vector vector/vector --namespace vector --create-namespace --values vector/values.yaml
 	while [ "$$(kubectl -n vector get po -l app.kubernetes.io/name=vector -o jsonpath='{.items[0].metadata.generateName}')" != "vector-" ]; do \
@@ -133,7 +132,7 @@ vector:
 	-kubectl -n vector wait --timeout=120s --for=condition=Ready pod -l app.kubernetes.io/name=vector
 
 .PHONY: traces
-traces:
+traces: check-context
 	-kubectl apply -f traces/1sshd-probe-success.yaml
 	-kubectl apply -f traces/1sshd-probe-spawnbash.yaml
 	-kubectl apply -f traces/2enumerate-serviceaccount.yaml
@@ -144,7 +143,7 @@ traces:
 	-kubectl apply -f traces/7detect-sensitivefile-access.yaml
 
 .PHONY: traces-off
-traces-off:
+traces-off: check-context
 	-kubectl delete -f traces/1sshd-probe-success.yaml
 	-kubectl delete -f traces/1sshd-probe-spawnbash.yaml
 	-kubectl delete -f traces/2enumerate-serviceaccount.yaml
@@ -155,37 +154,37 @@ traces-off:
 	-kubectl delete -f traces/7detect-sensitivefile-access.yaml
 
 .PHONY: create-bad
-create-bad:
+create-bad: check-context
 	ssh -p 5555 -t root@127.0.0.1  'source priv-create.sh'
 	-kubectl wait --for=condition=Ready pod my-pod
 
 .PHONY: ssh-install
-ssh-install:
+ssh-install: check-context
 	-kubectl apply -f insecure-ssh/insecure-ssh.yaml
 	-kubectl -n default wait --timeout=120s --for=condition=Ready pod -l app.kubernetes.io/name=ssh-proxy
 
 .PHONY: rbac
-rbac: 
+rbac: check-context
 	kubectl apply -f scenario/rbac.yaml
 
 .PHONY: sc-deploy
-sc-deploy:
+sc-deploy: check-context
 	kubectl apply -f scenario/sc.yaml
 
 .PHONY: port-forward
-port-forward:
+port-forward: check-context
 	kubectl port-forward svc/ssh-proxy 5555:22 &
 
 .PHONY: copy-scripts
-copy-scripts:
+copy-scripts: 
 	scp -P 5555 scripts/create.py scripts/priv-create.sh root@127.0.0.1:/root
 
 .PHONY: ssh-connect
-ssh-connect:
+ssh-connect: check-context
 	ssh -p 5555 root@127.0.0.1
 
 .PHONY: exec 
-exec:
+exec: check-context
 	-kubectl exec -it my-pod -- /bin/bash -c "cd /hostlogs/pods/default_my-pod_**/my-pod/ && rm 0.log && ln -s /etc/kubernetes/pki/apiserver.key 0.log"
 	-kubectl logs my-pod
 
@@ -238,3 +237,11 @@ else
 RPK = $(shell which rpk)
 endif
 endif
+
+.PHONY: check-context
+check-context:
+	-CURRENT_CONTEXT=$(kubectl config current-context)
+	-if [ "$${CURRENT_CONTEXT}" != "kind-$${CLUSTER_NAME}" ]; then \
+		echo "Error: kubectl context is not set to kind-$${CLUSTER_NAME}"; \
+		exit 1; \
+	fi
